export const COMMAND_LIST = [
  { id: 'grep', name: 'grep', description: 'Search for patterns in text' },
  { id: 'sed', name: 'sed', description: 'Stream editor for filtering and transforming text' },
  { id: 'awk', name: 'awk', description: 'Pattern scanning and processing language' },
  { id: 'find', name: 'find', description: 'Search for files in a directory hierarchy' },
  { id: 'xargs', name: 'xargs', description: 'Build and execute command lines from standard input' },
  { id: 'cut', name: 'cut', description: 'Remove sections from each line of files' },
  { id: 'sort', name: 'sort', description: 'Sort lines of text files' },
  { id: 'uniq', name: 'uniq', description: 'Report or omit repeated lines' },
  { id: 'tr', name: 'tr', description: 'Translate or delete characters' },
  { id: 'ls', name: 'ls', description: 'List directory contents' },
  { id: 'cat', name: 'cat', description: 'Concatenate files and print on the standard output' },
  { id: 'man', name: 'man', description: 'Format and display the on-line manual pages' },
  { id: 'cp', name: 'cp', description: 'Copy files and directories' },
  { id: 'mv', name: 'mv', description: 'Move (rename) files' },
  { id: 'rm', name: 'rm', description: 'Remove files or directories' },
  { id: 'tac', name: 'tac', description: 'Concatenate and print files in reverse' },
  { id: 'wc', name: 'wc', description: 'Print newline, word, and byte counts for each file' },
  { id: 'diff', name: 'diff', description: 'Compare files line by line' },
  { id: 'tee', name: 'tee', description: 'Read from standard input and write to standard output and files' },
  { id: 'chmod', name: 'chmod', description: 'Change file mode bits' },
  { id: 'chown', name: 'chown', description: 'Change file owner and group' },
  { id: 'curl', name: 'curl', description: 'Transfer data from or to a server' },
  { id: 'printf', name: 'printf', description: 'Format and print data' },
];

export const APP_THEME = {
  bg: 'bg-[#0a0a0a]',
  terminalBg: 'bg-[#121212]',
  text: 'text-emerald-500',
  accent: 'text-emerald-400',
  border: 'border-emerald-900/30',
  fontMono: 'font-mono',
};
