export const COMMAND_CATEGORIES = [
  { id: 'text', name: 'Text', icon: 'FileText' },
  { id: 'file', name: 'Files', icon: 'Folder' },
  { id: 'system', name: 'System', icon: 'Cpu' },
  { id: 'network', name: 'Network', icon: 'Globe' },
  { id: 'utility', name: 'Utilities', icon: 'Wrench' },
];

export const COMMAND_CATEGORY_GROUPS = [
  { id: 'data', name: 'Data Processing', icon: 'FileText', categories: ['text'] as const },
  { id: 'system_files', name: 'Files/System', icon: 'Folder', categories: ['system', 'file'] as const },
  { id: 'net_utils', name: 'Network/Utils', icon: 'Globe', categories: ['network', 'utility'] as const },
] as const;

export const COMMAND_LIST = [
  // Text
  { id: 'grep', name: 'grep', description: 'Search for patterns in text', category: 'text' },
  { id: 'sed', name: 'sed', description: 'Stream editor for filtering and transforming text', category: 'text' },
  { id: 'awk', name: 'awk', description: 'Pattern scanning and processing language', category: 'text' },
  { id: 'cut', name: 'cut', description: 'Remove sections from each line of files', category: 'text' },
  { id: 'sort', name: 'sort', description: 'Sort lines of text files', category: 'text' },
  { id: 'uniq', name: 'uniq', description: 'Report or omit repeated lines', category: 'text' },
  { id: 'tr', name: 'tr', description: 'Translate or delete characters', category: 'text' },
  { id: 'wc', name: 'wc', description: 'Print newline, word, and byte counts', category: 'text' },
  { id: 'printf', name: 'printf', description: 'Format and print data', category: 'text' },
  { id: 'head', name: 'head', description: 'Output the first part of files', category: 'text' },
  { id: 'tail', name: 'tail', description: 'Output the last part of files', category: 'text' },
  { id: 'nl', name: 'nl', description: 'Number lines of files', category: 'text' },
  { id: 'rev', name: 'rev', description: 'Reverse lines characterwise', category: 'text' },
  { id: 'tac', name: 'tac', description: 'Concatenate and print files in reverse', category: 'text' },
  { id: 'expand', name: 'expand', description: 'Convert tabs to spaces', category: 'text' },
  { id: 'unexpand', name: 'unexpand', description: 'Convert spaces to tabs', category: 'text' },
  { id: 'fmt', name: 'fmt', description: 'Simple optimal text formatter', category: 'text' },
  { id: 'fold', name: 'fold', description: 'Wrap each input line to fit in specified width', category: 'text' },
  { id: 'paste', name: 'paste', description: 'Merge lines of files', category: 'text' },
  { id: 'join', name: 'join', description: 'Join lines of two files on a common field', category: 'text' },
  { id: 'comm', name: 'comm', description: 'Compare two sorted files line by line', category: 'text' },
  { id: 'csplit', name: 'csplit', description: 'Split a file into sections determined by context lines', category: 'text' },
  { id: 'split', name: 'split', description: 'Split a file into pieces', category: 'text' },
  { id: 'shuf', name: 'shuf', description: 'Generate random permutations', category: 'text' },
  { id: 'column', name: 'column', description: 'Columnate lists', category: 'text' },
  { id: 'hexdump', name: 'hexdump', description: 'Display file contents in hexadecimal, decimal, octal, or ascii', category: 'text' },
  { id: 'strings', name: 'strings', description: 'Print the sequences of printable characters in files', category: 'text' },
  
  // Files
  { id: 'find', name: 'find', description: 'Search for files in a directory', category: 'file' },
  { id: 'ls', name: 'ls', description: 'List directory contents', category: 'file' },
  { id: 'cat', name: 'cat', description: 'Concatenate and print files', category: 'file' },
  { id: 'cp', name: 'cp', description: 'Copy files and directories', category: 'file' },
  { id: 'mv', name: 'mv', description: 'Move (rename) files', category: 'file' },
  { id: 'rm', name: 'rm', description: 'Remove files or directories', category: 'file' },
  { id: 'chmod', name: 'chmod', description: 'Change file mode bits', category: 'file' },
  { id: 'chown', name: 'chown', description: 'Change file owner and group', category: 'file' },
  { id: 'tar', name: 'tar', description: 'Manipulate tape archives', category: 'file' },
  { id: 'gzip', name: 'gzip', description: 'Compress or expand files', category: 'file' },
  { id: 'gunzip', name: 'gunzip', description: 'Decompress files', category: 'file' },
  { id: 'bzip2', name: 'bzip2', description: 'A block-sorting file compressor', category: 'file' },
  { id: 'bunzip2', name: 'bunzip2', description: 'Decompress bzip2 files', category: 'file' },
  { id: 'xz', name: 'xz', description: 'Compress or decompress .xz and .lzma files', category: 'file' },
  { id: 'unzip', name: 'unzip', description: 'List, test and extract compressed files in a ZIP archive', category: 'file' },
  { id: 'mkdir', name: 'mkdir', description: 'Create directories', category: 'file' },
  { id: 'rmdir', name: 'rmdir', description: 'Remove empty directories', category: 'file' },
  { id: 'touch', name: 'touch', description: 'Change file timestamps (often used to create empty files)', category: 'file' },
  { id: 'ln', name: 'ln', description: 'Make links between files', category: 'file' },
  { id: 'readlink', name: 'readlink', description: 'Print value of a symbolic link or canonical file name', category: 'file' },
  { id: 'realpath', name: 'realpath', description: 'Print the resolved path', category: 'file' },
  { id: 'basename', name: 'basename', description: 'Strip directory and suffix from filenames', category: 'file' },
  { id: 'dirname', name: 'dirname', description: 'Strip last component from file name', category: 'file' },
  { id: 'stat', name: 'stat', description: 'Display file or file system status', category: 'file' },
  { id: 'file', name: 'file', description: 'Determine file type', category: 'file' },
  { id: 'mktemp', name: 'mktemp', description: 'Create a temporary file or directory', category: 'file' },
  { id: 'dd', name: 'dd', description: 'Convert and copy a file', category: 'file' },
  { id: 'shred', name: 'shred', description: 'Overwrite a file to hide its contents, and optionally delete it', category: 'file' },
  { id: 'truncate', name: 'truncate', description: 'Shrink or extend the size of a file to the specified size', category: 'file' },
  
  // System
  { id: 'ps', name: 'ps', description: 'Report current processes', category: 'system' },
  { id: 'top', name: 'top', description: 'Display Linux processes', category: 'system' },
  { id: 'kill', name: 'kill', description: 'Send a signal to a process', category: 'system' },
  { id: 'df', name: 'df', description: 'Report disk space usage', category: 'system' },
  { id: 'du', name: 'du', description: 'Estimate file space usage', category: 'system' },
  { id: 'lsof', name: 'lsof', description: 'List open files', category: 'system' },
  { id: 'uptime', name: 'uptime', description: 'Tell how long the system has been running', category: 'system' },
  { id: 'free', name: 'free', description: 'Display amount of free and used memory', category: 'system' },
  { id: 'uname', name: 'uname', description: 'Print system information', category: 'system' },
  { id: 'hostname', name: 'hostname', description: 'Show or set the system\'s host name', category: 'system' },
  { id: 'id', name: 'id', description: 'Print real and effective user and group IDs', category: 'system' },
  { id: 'whoami', name: 'whoami', description: 'Print effective userid', category: 'system' },
  { id: 'who', name: 'who', description: 'Show who is logged on', category: 'system' },
  { id: 'w', name: 'w', description: 'Show who is logged on and what they are doing', category: 'system' },
  { id: 'groups', name: 'groups', description: 'Print the groups a user is in', category: 'system' },
  { id: 'dmesg', name: 'dmesg', description: 'Print or control the kernel ring buffer', category: 'system' },
  { id: 'journalctl', name: 'journalctl', description: 'Query and display logs from journald', category: 'system' },
  { id: 'systemctl', name: 'systemctl', description: 'Control the systemd system and service manager', category: 'system' },
  { id: 'killall', name: 'killall', description: 'Kill processes by name', category: 'system' },
  { id: 'pgrep', name: 'pgrep', description: 'Look up processes based on name and other attributes', category: 'system' },
  { id: 'pkill', name: 'pkill', description: 'Look up or signal processes based on name and other attributes', category: 'system' },
  { id: 'nice', name: 'nice', description: 'Run a program with modified scheduling priority', category: 'system' },
  { id: 'renice', name: 'renice', description: 'Alter priority of running processes', category: 'system' },
  { id: 'nohup', name: 'nohup', description: 'Run a command immune to hangups', category: 'system' },
  { id: 'timeout', name: 'timeout', description: 'Run a command with a time limit', category: 'system' },
  { id: 'sleep', name: 'sleep', description: 'Delay for a specified amount of time', category: 'system' },
  { id: 'watch', name: 'watch', description: 'Execute a program periodically, showing output fullscreen', category: 'system' },
  { id: 'date', name: 'date', description: 'Print or set the system date and time', category: 'system' },
  { id: 'bc', name: 'bc', description: 'An arbitrary precision calculator language', category: 'system' },
  { id: 'expr', name: 'expr', description: 'Evaluate expressions', category: 'system' },
  { id: 'seq', name: 'seq', description: 'Print a sequence of numbers', category: 'system' },
  
  // Network
  { id: 'curl', name: 'curl', description: 'Transfer data from or to a server', category: 'network' },
  { id: 'ssh', name: 'ssh', description: 'OpenSSH SSH client', category: 'network' },
  { id: 'scp', name: 'scp', description: 'Secure copy (remote file copy)', category: 'network' },
  { id: 'netstat', name: 'netstat', description: 'Print network connections', category: 'network' },
  { id: 'ping', name: 'ping', description: 'Send ICMP ECHO_REQUEST to network hosts', category: 'network' },
  { id: 'dig', name: 'dig', description: 'DNS lookup utility', category: 'network' },
  { id: 'ip', name: 'ip', description: 'Show / manipulate routing, network devices, interfaces and tunnels', category: 'network' },
  { id: 'ss', name: 'ss', description: 'Another utility to investigate sockets', category: 'network' },
  { id: 'wget', name: 'wget', description: 'The non-interactive network downloader', category: 'network' },
  { id: 'rsync', name: 'rsync', description: 'Fast, versatile, remote (and local) file-copying tool', category: 'network' },
  { id: 'nc', name: 'nc', description: 'Arbitrary TCP and UDP connections and listens', category: 'network' },
  { id: 'host', name: 'host', description: 'DNS lookup utility', category: 'network' },
  { id: 'nslookup', name: 'nslookup', description: 'Query Internet name servers interactively', category: 'network' },
  
  // Utilities
  { id: 'man', name: 'man', description: 'An interface to the system reference manuals', category: 'utility' },
  { id: 'whatis', name: 'whatis', description: 'Display one-line manual page descriptions', category: 'utility' },
  { id: 'whereis', name: 'whereis', description: 'Locate the binary, source, and manual page files for a command', category: 'utility' },
  { id: 'which', name: 'which', description: 'Locate a command', category: 'utility' },
  { id: 'env', name: 'env', description: 'Run a program in a modified environment', category: 'utility' },
  { id: 'printenv', name: 'printenv', description: 'Print all or part of the environment', category: 'utility' },
  { id: 'sudo', name: 'sudo', description: 'Execute a command as another user', category: 'utility' },
  { id: 'su', name: 'su', description: 'Run a command with substitute user and group ID', category: 'utility' },
  { id: 'clear', name: 'clear', description: 'Clear the terminal screen', category: 'utility' },
  { id: 'xargs', name: 'xargs', description: 'Build and execute command lines from standard input', category: 'utility' },
  { id: 'sh', name: 'sh', description: 'Shell command language interpreter', category: 'utility' },
  { id: 'apt', name: 'apt', description: 'Command-line interface for the package management system', category: 'utility' },
  { id: 'apt-get', name: 'apt-get', description: 'APT package handling utility - command-line interface', category: 'utility' },
  { id: 'git', name: 'git', description: 'Version control system content tracker', category: 'utility' },
  { id: 'openssl', name: 'openssl', description: 'OpenSSL command line tool', category: 'utility' },
  { id: 'xxd', name: 'xxd', description: 'Make a hexdump or do the reverse', category: 'utility' },
  { id: 'yes', name: 'yes', description: 'Output a string repeatedly until killed', category: 'utility' },
];

export const APP_THEME = {
  bg: 'bg-[#0a0a0a]',
  terminalBg: 'bg-[#121212]',
  text: 'text-emerald-500',
  accent: 'text-emerald-400',
  border: 'border-emerald-900/30',
  fontMono: 'font-mono',
};
